# -*- mode: shell-script -*-
# load common environment variables
export LC_ALL=en_US.UTF-8
export LANG=en_US.UTF-8

# if this is an interactive shell load bashrc
case "$-" in *i*)
        if [ -r ${HOME}/.bashrc ]; then . ${HOME}/.bashrc; fi;;
esac
